# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpsight" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "03860a2ca4fced88c0162839ab57a11b45f86bf87d030db3fc8b7a865ebc18be"
      url "https://github.com/greyquill/mcpsight/releases/download/v#{version}/mcpsight_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d2d6ac8c3ec30ae6cc81a271d5d539fc4860b10676fe3b4796d911c6d9b212b"
      url "https://github.com/greyquill/mcpsight/releases/download/v#{version}/mcpsight_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a860571de4d5fed902074d9033bd43e97e28dd42f6edee4dc42774d9cdecadb3"
      url "https://github.com/greyquill/mcpsight/releases/download/v#{version}/mcpsight_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "869e310ad584fd58f191bfba9d36db17225fcf9ea5295e282342caafe3897a4f"
      url "https://github.com/greyquill/mcpsight/releases/download/v#{version}/mcpsight_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpsight"
  desc "Inspect an MCP server before you trust it"
  homepage "https://mcpsight.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpsight"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpsight"]
    end
  end

  # No zap stanza required
end
